[View in Colaboratory](https://colab.research.google.com/github/Krishna24s/assignment1/blob/master/assignment2.ipynb)

In [0]:
import numpy as np
import math

In [2]:
#Question 1
a=np.random.rand(10,1)
print(a)
a.mean()

[[0.25374478]
 [0.45722201]
 [0.17112835]
 [0.8330767 ]
 [0.99520359]
 [0.1770944 ]
 [0.562675  ]
 [0.88708103]
 [0.19354675]
 [0.1674083 ]]


0.46981808956150395

In [3]:
#Question 2
b=np.random.rand(20,1)
print(b)
b.var()

[[0.44675797]
 [0.45606489]
 [0.25872808]
 [0.1867262 ]
 [0.17761124]
 [0.42463478]
 [0.47778063]
 [0.11956852]
 [0.68183184]
 [0.15335014]
 [0.05904823]
 [0.76015769]
 [0.80033426]
 [0.99534752]
 [0.8736643 ]
 [0.82749238]
 [0.41499733]
 [0.11051076]
 [0.54175614]
 [0.77336683]]


0.08192786414044063

In [4]:
#Question 3
A=np.random.rand(10,20)
print(A)
B=np.random.rand(20,25)
print(B)
C=np.dot(A,B)
print(C)

[[1.96406375e-01 2.10355233e-01 9.28752729e-01 9.11426138e-01
  7.62709350e-01 8.52367566e-01 4.85557618e-01 1.47463378e-01
  5.38914257e-01 7.21002376e-01 4.35118258e-01 3.65453289e-01
  3.28474580e-01 1.67121237e-01 9.58997926e-01 7.59384993e-01
  3.89899742e-01 8.92620150e-01 9.16685911e-01 6.54767520e-01]
 [9.88717551e-02 9.09742850e-01 1.81094566e-02 7.05131632e-01
  7.77236413e-01 2.70780980e-01 5.77806917e-01 4.90331433e-01
  3.30064257e-01 1.19734390e-01 7.86210017e-01 1.82594472e-01
  5.03386909e-01 4.94460795e-01 4.55287926e-01 4.82677860e-01
  4.82278229e-02 2.51482470e-01 9.95740681e-01 3.94566880e-01]
 [2.02967079e-01 4.15604586e-02 5.67944777e-01 2.97124011e-01
  5.61547999e-01 3.28552578e-01 4.75086735e-01 1.83721918e-01
  6.43764014e-01 4.07927464e-01 1.00800918e-01 1.01987171e-01
  8.61678415e-02 7.85203296e-01 6.78733433e-01 3.81360827e-01
  4.24640806e-01 1.14037476e-01 9.24914501e-01 8.75237833e-01]
 [9.50595388e-01 1.00271620e-01 2.46791910e-01 2.95267357e-01
  8.1

In [5]:
#Question 4
b=np.arange(10).reshape(10,1)
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [6]:
def f(x):
    return 1 / (1 + math.exp(-x))
np.apply_along_axis(f,1,b)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])