[View in Colaboratory](https://colab.research.google.com/github/Krishna24s/assignment1/blob/master/assignment3.ipynb)

In [5]:
import numpy as np
import math

In [2]:
#Question 1
a=np.random.rand(10,1)
print(a)
a.mean()

[[0.86031724]
 [0.05863212]
 [0.25110836]
 [0.40047641]
 [0.29565256]
 [0.20752183]
 [0.34041456]
 [0.07310004]
 [0.75319858]
 [0.83653595]]


0.40769576617612807

In [3]:
#Question 2
b=np.random.rand(20,1)
print(b)
b.var()

[[0.66631124]
 [0.73625212]
 [0.10219779]
 [0.13547182]
 [0.60634205]
 [0.06839303]
 [0.09673604]
 [0.18524924]
 [0.86838567]
 [0.08086643]
 [0.42451052]
 [0.90021572]
 [0.42781396]
 [0.36309238]
 [0.80470309]
 [0.5764692 ]
 [0.99419842]
 [0.34455004]
 [0.09133633]
 [0.54639661]]


0.09116344055950773

In [4]:
#Question 3
A=np.random.rand(10,20)
print(A)
B=np.random.rand(20,25)
print(B)
C=np.dot(A,B)
print(C)

[[0.31506832 0.06605894 0.61231801 0.90372319 0.591643   0.21225313
  0.67679792 0.68635674 0.35170196 0.31154347 0.64164764 0.13594408
  0.43879133 0.4625459  0.86713863 0.02034926 0.00354767 0.84927849
  0.81700564 0.78885099]
 [0.79392644 0.0404392  0.0627021  0.7690308  0.7993487  0.36623149
  0.39137842 0.46569444 0.98272913 0.37184733 0.10382875 0.28673682
  0.66843177 0.3863007  0.57084023 0.45660317 0.1584872  0.3943372
  0.73325991 0.06310219]
 [0.80384155 0.77739177 0.98957958 0.46927825 0.92571685 0.07373668
  0.16671346 0.29288163 0.1900559  0.37011709 0.19264774 0.04719161
  0.04906689 0.49756614 0.19841805 0.93640177 0.95130989 0.80161365
  0.75455616 0.64593966]
 [0.90004673 0.28099514 0.88297559 0.15680083 0.289414   0.96578182
  0.09008199 0.79457209 0.85359395 0.53144028 0.91679528 0.29339095
  0.79150025 0.98104098 0.69955317 0.79821941 0.7335282  0.2180697
  0.15989999 0.04852895]
 [0.76642863 0.19921972 0.37748484 0.2395913  0.73941314 0.70240916
  0.82595547 0.158

In [5]:
#Question 4
b=np.arange(10).reshape(10,1)
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [7]:
def f(x):
    return 1 / (1 + math.exp(-x))
np.apply_along_axis(f,1,b)

NameError: ignored

In [1]:
#Question 1
pA=0.30
pB=0.16
pAifB=0.05
pBifA=(pAifB*pB)/pA
print(pBifA)

0.0266666666667


In [2]:
#Question 2
bag1=1.0/2 #probability of selecting bag1
bag2=1.0/2 #probability of selecting bag2
black1=6.0/10 #probability of selecting black ball from bag1
black2=3.0/7 #probability of selecting black ball from bag2
pblack1=(bag1*black1)/((bag1*black1)+(bag2*black2))
print(pblack1)

0.583333333333


In [3]:
#Question 3
truth=2.0/3 #probability of speaking truth
lie=1.0/3 #probability of speaking lie
p4=1.0/6 #probability of number obtained is 4
pn4=5.0/6 #probability of number obtained is not 4
probab=(truth*p4)/((truth*p4)+(lie*pn4))
print(probab)

0.285714285714
